spring.application.name=wallet
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=kaiserdapar
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

spring.web.error.include-message=always